name: fl_command
description: Command line integration conversion with support for ADB and SCRCPY
version: 1.0.2
repository: https://github.com/Wayaer/fl_command.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.13.3 #shell命令库
  synchronized: ^3.1.0+1 #同步库
  path_provider: ^2.1.1 #路径库
  archive: ^3.3.0 # 压缩与解压缩库
  dio: ^5.4.0 #网络请求库

dev_dependencies:
  flutter_lints: ^3.0.1