name: fl_command
description: Command line integration conversion with support for ADB and SCRCPY
version: 0.0.1
repository: https://github.com/Wayaer/fl_command.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  process_run: ^0.12.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: